name: Phase 3 Build & Test (Linux)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push: 
    tags:
    - phase3*
    - phase-3*
  release:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Dependencies installed?
        run: sudo apt-get update && sudo apt-get install -y bison flex gcc libfl-dev wget
      - name: wget mil_run
        run: |
          cd $GITHUB_WORKSPACE/p_III/
          wget -o mil_run https://www.cs.ucr.edu/~mafar001/compiler/webpages3/mil_run
      - name: build parser
        run: |
          cd $GITHUB_WORKSPACE/p_III/
          mil_run mil_code.mil < input.txt
      # Runs a set of commands using the runners shell
      - name: now test it according to project specifications
        run: |
          cd $GITHUB_WORKSPACE/p_III/
          cat fibonacci.min | ./boz > test1
