name: Phase 3 Build & Test (Linux)

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push: 
    tags:
    - phase3*
    - phase-3*
  release:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build-and-deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Dependencies installed?
        run: sudo apt-get update && sudo apt-get install -y bison flex gcc libfl-dev wget
      - name: wget mil_run.mil into tests/ and run it through interpreter
        run: |
          cd $GITHUB_WORKSPACE/P3-code_generation/
          wget -o tests/mil_run.mil https://www.cs.ucr.edu/~mafar001/compiler/webpages3/mil_run
          mil_run tests/mytest.mil
      - name: test 1 output to input.txt
        run: |
          cd $GITHUB_WORKSPACE/P3-code_generation/
          touch tests/input.txt && touch tests/fibout.mil
          make clean
          make
          echo 'run executable fibonacci.min -> output fibout.mil'
          ./minil tests/fibonacci.min > tests/fibout.mil
          echo 'fibout.mil -> input.txt'
          ./mil_run tests/fibout.mil < tests/input.txt
          cat tests/input.txt
      # Runs a set of commands using the runners shell
      - name: let's try the last tests
        run: |
          cd $GITHUB_WORKSPACE/P3-code_generation/
          cat tests/fibonacci.min | ./minil > test1
          cat tests/fibonacci.min | minil
          echo 5 > tests/input.txt mil_run tests/fibonacci.mil < tests/input.txt
